const CONSTANTS = {
  "admin": "Admin",
  "user": "User",
  "serviceProvider": "Service Provider",
  "create": "create",
  "read": "read",
  "update": "update",
  "delete": "delete",
  "post": "post",
  "get": "get",
  "put": "put",
  "active": "Active",
  "old": "Old",
  "newUserSubject": "Activate Your Account - fleeka",
  "newServiceProviderNotificationSubject": "New Service Provider has been registered with fleeka",
  "signupSuccess": "Welcome to fleeka! We have sent you an email with verification link, Please verify your email!",
  "activationMailfailed": "Sending verification mail failed!",
  "failedToMailFleeka": "Sending notification mail to fleeka is faled",
  "registrationConfirmation": "Confirmation for registration",
  "confirmationMailfailed": "Sending confirmation mail failed",
  "confirmationMailSuccess": "Your Registration is under review and a member of fleeka will contact you shortly",
  "emailUniqueError": "Email already in use, try with another one",
  "phoneNumberUniqueError": "Phone number in use, try with another one",
  "emailRequired": "Email is required",
  "phoneNumberRequired": "Phone number is required",
  "firstNameRequired": "First Name is required",
  "passwordRequired": "Password is required",
  "invalidEmail": "Email address is invalid",
  "invalidName": "Name is invalid",
  "invalidPhoneNumber": "Phone number is invalid",
  "establishmentNameRequired": "Establishment name is required",
  "invalidEstablishmentName": "Establishment Name should be between 2 to 50 characters",
  "serviceTypeRequired": "Service Type is required",
  "userActivated": "Your account has been activated successfully. You can login now using your credentials",
  "serviceProviderActivated": "Service Provider has been activated successfully",
  "somethingWentWrong": "Something went wrong, please contact administrator",
  "noUserFound": "Isn't in our system. Make sure you typed your email and password correctly.",
  "notActivated": "Account has not been activated",
  "noRecordFound": "No detiails found with the given data",
  "roleNotFound": "Unabel to find Role for this user",
  "unauthorizedAccess": "Unauthorized Access",
  "addPackageSuccess": "Packages are added successfully",
  "packageAssignError": "Packages can not assign to a User",
  "userDontHavePackage": "User do not have packages.",
  "noPrivilage": "You don't have privilege to do this action",
  "updatedSuccessfully": "Updated Successfully",
  "noServiceTypeFound": "We don't have info",
  "noVoucherFound": "Voucher is not avilable",
  "reserved": "Reserved",
  "used": "Used",
  "expired": "Expired",
  "activationPinNotMatch": "Invalid Activation PIN",
  "voucherActivate": "Voucher Activated Successfully",
  "pinUpdated": "Activation PIN Updated Successfully",
  "scheduleError": "Error While Updating the data through schedule Job",
  "scheduleSuccess": "Vouchers Updated Successfully through schedule Job",
  "noVouchersFound": "No vouchers found to update thorugh schedule job",
  "wrongPassword": "Wrong password entered",
  "passwordChanged": "Password has been changed successfully",
  "forgetPassword": "fleeka password reset",
  "passwordResetMailFailed": "Sending password reset link failed",
  "passwordResetMailSuccess": "An email has been sent with further instructions",
  "invalidResetPasswordToken": "Password reset token is invalid or has expired",
  "passwordResetSuccess": "Password reset has been completed",
  "passwordLength": "Password is shorter than the minimum allowed length",
  "resetTitle": "fleeka reset password",
  "selectServiceProvider": "Please select service provider",
  "selectVoucher": "Please select voucher",
  "reservedSuccessfully": "Voucher successfully reserved",
  "noServiceProviderFound": "No service provider found",
  "voucherAvailedSuccessfully": "Vouched availed successfully",
  "reviewAdded": "Review is in pending",
  "one": "1",
  "two": "2",
  "three": "3",
  "blank": ""
}

module.exports = { CONSTANTS };